[package]
name = "wikid"
version = "3.1.1"
edition = "2021"
authors = ["sharkthakftw"]
description = "feature-rich terminal wikipedia client"
license = "MIT"
repository = "https://github.com/sharkthakftw/wikid"
readme = "README.md"
keywords = ["wikipedia", "tui", "ratatui", "terminal", "reader"]
categories = ["command-line-utilities"]

[dependencies]
ratatui = "0.26.1"
crossterm = "0.27.0"
ureq = { version = "2.10", default-features = false, features = ["json", "tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tl = "0.7.8"
unicode-width = "0.1"
toml = "0.8.23"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
fast_qr = { version = "0.14", default-features = false }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
